version: '2'

services:
  web:
    build: .
    image: eriksf/compose-flask:0.2
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - SERVICE_USER
      - SERVICE_PASSWORD
    ports:
      - "5500:5500"
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - demo_network
  redis:
    image: redis
    networks:
      - demo_network

networks:
  demo_network:
    external:
      name: dockernet
